### ISSUE TITLE
Why nslookup can't resolv short name?

### ISSUE THREAD

**Issue by likunbyl** [docker-library/busybox#27] opened 2017-04-18 09:35 UTC
I'm using the newest container of busybox to run nslookup, but can't get short name resolved. any hints?
# nslookup nginx
Server:    192.168.192.10
Address 1: 192.168.192.10 kube-dns.kube-system.svc.cluster.local

nslookup: can't resolve 'nginx'

# nslookup nginx.policy-demo.svc.cluster.local
Server:    192.168.192.10
Address 1: 192.168.192.10 kube-dns.kube-system.svc.cluster.local

Name:      nginx.policy-demo.svc.cluster.local
Address 1: 192.168.204.48 nginx.policy-demo.svc.cluster.local

My /etc/resolv.conf is like this:
 # cat /etc/resolv.conf
nameserver 192.168.192.10
search policy-demo.svc.cluster.local svc.cluster.local cluster.local
options ndots:5

**Comment by tianon** [comment] 2017-04-25 21:33
I can't seem to reproduce with any of our three variants. :disappointed:
```console
$ docker network create test
32024cd09daca748f8254468f4f00893afc2e1173c378919b1f378ed719f1618
$ docker run -dit --name nginx --network test nginx:alpine
7feaf1f0b4f3d421603bbb984854b753c7cbc6b581dd0a304d3b8fccf8c6604b
$ docker run -it --rm --network test busybox:uclibc nslookup nginx
Server:    127.0.0.11
Address 1: 127.0.0.11

Name:      nginx
Address 1: 172.22.0.2 nginx.test
$ docker run -it --rm --network test busybox:glibc nslookup nginx
Server:    127.0.0.11
Address 1: 127.0.0.11

Name:      nginx
Address 1: 172.22.0.2 nginx.test
$ docker run -it --rm --network test busybox:musl nslookup nginx
nslookup: can't resolve '(null)'

Name:      nginx
Address 1: 172.22.0.2 nginx.test
```

**Comment by likunbyl** [comment] 2017-04-26 06:38
Thank you, tianon

With busybox:glibc, I can resolve the short name too:
```
$ kubectl exec busybox1 -- nslookup kubernetes                                 
Server:    192.168.192.10
Address 1: 192.168.192.10 kube-dns.kube-system.svc.cluster.local

Name:      kubernetes
Address 1: 192.168.192.1 kubernetes.default.svc.cluster.local
```
busybox1 is based on busybox:glibc

With busybox:lastest, I can't 
```
$ kubectl exec busybox -- nslookup kubernetes                                            
nslookup: can't resolve 'kubernetes'
Server:    192.168.192.10
Address 1: 192.168.192.10 kube-dns.kube-system.svc.cluster.local
```
busybox is based on busybox:latest

**Comment by tianon** [comment] 2017-05-04 20:03
Ah, it's not specific to short names, but DNS search paths; here's a better example for reproducing:
```console

$ docker network create --internal test
66b1bf0bf05cec6d32c171cc601b6ee160bb94de670b0c61a0a15ae267302d06

$ docker run -dit --name nginx.domain --network test nginx:alpine448e9b11cfb336464494c615be81db3058431f623eb9416507f5f46e19b2455c

$ docker run -it --rm --network test --dns-search domain busybox:glibc nslookup nginx
Server:    127.0.0.11
Address 1: 127.0.0.11

Name:      nginx
Address 1: 172.22.0.2 nginx.domain.test

$ docker run -it --rm --network test --dns-search domain busybox:uclibc nslookup nginx
Server:    127.0.0.11
Address 1: 127.0.0.11

nslookup: can't resolve 'nginx'

$ docker run -it --rm --network test --dns-search domain busybox:musl nslookup nginx
nslookup: can't resolve '(null)'

nslookup: can't resolve 'nginx'

```

(`busybox:uclibc` is `busybox:latest`)

:disappointed:

Not sure where to start digging on this one. :confused:

**Comment by vcunat** [comment] 2018-02-23 07:42
The implementation is broken with non-glibc, reportedly due to fiddling with its internals: https://dev.openwrt.org/ticket/18333

**Comment by wglambert** [comment] 2018-07-17 22:19
Seems only uclibc is broken now

```console
$ docker network create --internal test
d0f3b32461787a7d830cb7f73504db08a563dddbe1a93079bcd7b4034f7736de

$ docker run -dit --name nginx --network test nginx:alpine
bb795c7ddcee2043f1e4c6ce41d292af6e8497c29e80777f267864145052b345

$ docker run -it --rm --network test --dns-search domain busybox:glibc nslookup nginx
Server:         127.0.0.11
Address:        127.0.0.11:53

Non-authoritative answer:

Non-authoritative answer:
Name:   nginx
Address: 172.22.0.2

$ docker run -it --rm --network test --dns-search domain busybox:uclibc nslookup nginx
Server:         127.0.0.11
Address:        127.0.0.11:53

Non-authoritative answer:

*** Can't find nginx: No answer

$ docker run -it --rm --network test --dns-search domain busybox:musl nslookup nginx
Server:         127.0.0.11
Address:        127.0.0.11:53

Non-authoritative answer:

Non-authoritative answer:
Name:   nginx
Address: 172.22.0.2
```

**Comment by tianon** [comment] 2018-07-20 20:52
How does this relate to https://github.com/docker-library/busybox/issues/48?  Are they the same issue?

**Comment by tianon** [comment] 2018-07-20 21:03
From what I can tell, the new resolver in BusyBox's `nslookup` doesn't support DNS search domains at all, which seems like a pretty hefty regression.

**Comment by tianon** [comment] 2018-07-20 21:05
(See https://bugs.busybox.net/show_bug.cgi?id=11161 for where this is filed upstream.)

I'm going to close this in favor of #48, where there's been slightly more recent discussion. :+1:

**Closed by tianon** 2018-07-20 21:05 UTC
Labels: Issue
