### ISSUE TITLE
nc server does not quit on client disconnection

### ISSUE THREAD

**Issue by bergwolf** [docker-library/busybox#44] opened 2018-02-06 02:14 UTC
If we run nc in listen mode w/o the `-k` option, it is supposed to only serve one client and quit when the client disconnects. However, in latest version of the busybox image (`1.28.0`, image id `5b0d59026729`), the listen mode nc does not quit in such case:

### Reproducer
In one terminal, start nc in listen mode,
```
$docker run -it --rm --name nctest busybox sh -c 'nc -l -p 1300'
```
In another terminal, connect and quit,
```
$docker exec nctest nc localhost 1300
^C
```
### Expected Results
The `nctest` container in the first terminal is supposed to quit, but it doesn't.

It was working with older version of busybox (e.g., hash tag `efe10ee6727f`) but the current `latest` fails to quit.

**Comment by teawater** [comment] 2018-02-06 04:41
Reproduced the issue with upstream busybox and reported it in https://bugs.busybox.net/show_bug.cgi?id=10746

**Comment by tianon** [comment] 2018-02-06 04:46
Awesome, thanks teawater!

(Closing since this is an upstream bug, not something we can fix in the image. 👍)

**Closed by tianon** 2018-02-06 04:46 UTC
